name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-static-library:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure (CMake preset: release)
        run: cmake --preset release

      - name: Build (CMake preset: release)
        run: cmake --build --preset release
